projectRS/patient/urls.py
from django.urls import path
from .import views

urlpatterns = [
    #path('', views.index, name='index'),
    path('review', views.review, name='reviewform'),
    #path('', views.patient name='Patientform'),
    path('', views.profile, name='Profiletform'),
]

projectRS/projectRS/urls.py
from argparse import Namespace
from unicodedata import name
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('patient/', include('patient.urls'), name = "patient"),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

projectRS/patient/models.py
from logging import WARN
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
import os


class Wilaya(models.Model):
    WilayaName = models.CharField(max_length=50,blank=True)
    def __str__(self):
        return self.WilayaName
# Create your models here.
class Patient(models.Model):  
    GENDER=(
            ('Male','Male '),
            ('Female','Female '),
            )
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    numTel=models.IntegerField(null=True,blank=True)
    gender = models.CharField(max_length=10,blank=False,choices=GENDER,default='male ')
    med_history = models.TextField(max_length=800, blank=True)
    Wilaya = models.ForeignKey(Wilaya, blank=True, null=True, on_delete=models.CASCADE)
    poids = models.IntegerField(null=False,blank=False)
    taille = models.IntegerField(null=False,blank=False)
    preg = models.BooleanField(null=False,blank=False, default=0)

    def __str__(self):
        return self.user.username 



class ListDrug(models.Model):
    drugName = models.CharField(max_length=50,blank=True)
    def __str__(self):
        return self.drugName


class ListCondition(models.Model):
    condition = models.CharField(max_length=50,blank=True)
    def __str__(self):
        return self.condition

class ListSideEffect(models.Model):
    SideEff = models.CharField(max_length=50,blank=True)
    def __str__(self):
        return self.condition


class PatientSideEffect(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    drugName = models.ForeignKey(
        ListDrug, blank=True, null=True, on_delete=models.CASCADE)
    condition = models.ForeignKey(
        ListCondition, blank=True, null=True, on_delete=models.CASCADE)
    SideEff = models.ForeignKey(
        ListSideEffect, blank=True, null=True, on_delete=models.CASCADE)
    dateDebut = models.DateField()
    datefin = models.DateField()
    Evolution = models.CharField(max_length=50)
    Description = models.CharField(max_length=8000)
    otherDrug = models.CharField(max_length=50)
    date = models.DateField(auto_now=False, auto_now_add=True)
    #incr = models.IntegerField(default=1)

    def __str__(self):
        return '%s %s %s' % (self.user ,self.drugName, self.SideEff)





class Review(models.Model):

    Rating=((1,'1'),(2,'1'),(3,'3'),(4,'4'),(5,'5'))
    

    drugName = models.CharField(max_length=50)
    condition = models.CharField(max_length=50)
    review = models.CharField(max_length=500)
    rating = models.IntegerField(blank=False,choices=Rating,default="3")
    #rating = models.IntegerField(blank=False,default="3")
    date = models.DateField(auto_now=False, auto_now_add=True)
    usefulCount = models.IntegerField(default=0)
    def __str__(self):
        return self.drugName




class SideEffect(models.Model):

    drugName = models.CharField(max_length=50)
    condition = models.CharField(max_length=50)
    se = models.CharField(max_length=50)
    freq = models.DecimalField(max_digits = 5,decimal_places = 2)
    incr = models.IntegerField(default=0)

    def __str__(self):
        return '%s %s' % (self.drugName, self.condition)

projectRS/patient/forms.py
from django import forms
from .models import Review,Patient,SideEffect
from django.forms import ModelForm
from datetime import date
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView,UpdateView,DeleteView


class CreateUserForm(UserCreationForm):
        email = forms.EmailField(required=True, help_text='Required.',widget=forms.EmailInput(attrs={'class':'form-control',
                        'placeholder':'Email...'}))
        first_name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
                            'placeholder':'First name...'}))
        last_name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
                            'placeholder':'Last name...'}))
        username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
                            'placeholder':'Username...'}))
        class Meta:
            model = User
            fields = ['username','first_name','last_name','email','password1','password2',]
            
        def save(self,commit=True):
            user=super().save(commit=False)

            user.email=self.cleaned_data['email']
            user.first_name=self.cleaned_data['first_name']
            user.last_name=self.cleaned_data['last_name']

            if commit: 
                user.save()
            return user    


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['birth_date','numTel','gender','med_history','Wilaya','poids','taille','preg',
                    ]
        labels = {
            'med_history':'antecedent',
            'preg':'grossesse',
                }
                                        
        widgets = {            
                        'med_history':forms.TextInput(attrs={'class':'form-control',
                                    'placeholder':'Historique médicale, antécédant ...'}),
                        'gender':forms.Select(attrs={'class':'form-control',
                                    'placeholder':'gender ...'}),
                        'Wilaya':forms.Select(attrs={'class':'form-control',
                                    'placeholder':'Selectionner votre Wilaya...'}),
                        'birth_date':forms.TextInput(attrs={'class':'form-control',
                                    'placeholder':'YYYY-MM-DD.'}),
                    }

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField( widget=forms.PasswordInput)

class Reviewform(forms.ModelForm): 
    class Meta:
        model = Review
        fields = [
            "drugName","condition","review","rating",
        ]
        labels = {
            "drugName":"Drug Name",
            "condition":"condition",
            "review":"review",
            "rating":"rating",
            "usefulCount":"usefulCount",
        }
        widgets = {
            "drugName":forms.TextInput(attrs={'class':'form-control',
                                    'placeholder':'Insert Drug Name'}),
            "condition":forms.TextInput(attrs={'class':'form-control',
                                    'placeholder':'In Drug Name.'}),
            "review":forms.Textarea(attrs={'class':'form-control',
                                    'placeholder':'review...'}),   
                    }

projectRS/patient/views.py
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import render
#from django.urls import path 
from datetime import datetime
from .forms import PatientForm,Reviewform,CreateUserForm
from .models import Review,PatientSideEffect,Patient


#def index(request):
#   return render(request, 'reviewForm.html')

def review(request):
    #form = Reviewform()

    if request.method == 'POST': 
        formR = Reviewform(request.POST)
        if formR.is_valid() :
            Review =formR.save(commit=False)
            Review.drugName=formR.cleaned_data.get('drugName')
            Review.condition=formR.cleaned_data.get('condition')
            Review.review=formR.cleaned_data.get('review')
            Review.rating=formR.cleaned_data.get('rating')
            
            Review.save()
            formR.save_m2m()
            print('review created')

    else:
            formR = Reviewform()
    context = {'formR':formR}
    return render(request, 'reviewForm.html',context)

def patient(request):
    
    #P_form=PatientForm()
    if request.method == 'POST':
        P_form = PatientForm(request.POST)
        if P_form.is_valid():
            Patient =P_form.save(commit=False)
            Patient.birth_date=P_form.cleaned_data.get('drugName')
            Patient.numTel=P_form.cleaned_data.get('condition')
            Patient.gender=P_form.cleaned_data.get('review')
            Patient.med_history=P_form.cleaned_data.get('rating')
            Patient.Wilaya=P_form.cleaned_data.get('condition')
            Patient.poids=P_form.cleaned_data.get('review')
            Patient.taille=P_form.cleaned_data.get('rating')
            Patient.preg=P_form.cleaned_data.get('rating')
            
            Patient.save()
            P_form.save_m2m()
            print('patient created')
    else:
        P_form = PatientForm()
    
    context = {'P_form':P_form}

    return render(request,'PatientForm.html',context)



def profile(request):

    if request.method == 'POST':
        form=CreateUserForm(request.POST)
        profile_form = PatientForm(request.POST)

        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            #user.save_m2m() #maybe this is the error

            profile = profile_form.save(commit=False)
            profile.user=user

            user.med_history = profile_form.cleaned_data.get('med_history')
            user.numTel = profile_form.cleaned_data.get('numTel')
            user.gender = profile_form.cleaned_data.get('gender')
            user.Wilaya = profile_form.cleaned_data.get('Wilaya')
            user.poids = profile_form.cleaned_data.get('poids')
            user.taille = profile_form.cleaned_data.get('taille')
            user.birth_date = profile_form.cleaned_data.get('birth_date')
            user.preg = profile_form.cleaned_data.get('preg')
            profile.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=password)
            login(request, user)

            print('user created')
            messages.add_message(request, messages.SUCCESS , "You have Registered successfully" )
            #return redirect('home:home')
    else:
        form=CreateUserForm()
        profile_form = PatientForm()
            
            
            
    context = {'form' : form, 'profile_form' : profile_form }
    return render(request, 'profile.html', context) 

projectRS/patient/templates/PatientForm.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Review</title>
</head>
<body>
    welcome <table>
                <form method="post">
                    {% csrf_token %}
                    {{P_form.as_table}}
                        <tr>
                            <td>
                                <button type="submit"> Submit </button>
                            </td>
                        </tr>
                </form>
            </table>
    
</body>
</html>
{% endblock %}

projectRS/patient/templates/profile.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Review</title>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
</head>
<style>
    #id_Wilaya {
        width: 100%;
    }
</style>
<body>
    welcome <table>
                <form method="post">
                    {% csrf_token %}
                    {{form.as_table}}
                    {{profile_form.as_table}}
                    <tr>
                            <td>
                                <button type="submit"> Submit </button>
                            </td>
                        </tr>
                </form>
            </table>
            <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
            <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        
            <script>
                    $(document).ready(function() {
                    $('#id_Wilaya').select2();
                        });
            </script>
    
</body>
</html>
{% endblock %}

projectRS/patient/templates/reviewForm.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Review</title>
</head>
<body>
    welcome <table>
                <form method="post">
                    {% csrf_token %}
                    {{formR.as_table}}
                        <tr>
                            <td>
                                <button type="submit"> Submit </button>
                            </td>
                        </tr>
                </form>
            </table>
    
</body>
</html>
{% endblock %}

projectRS/patient/templates/sidedeclare.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Review</title>
</head>
<body>
    welcome <table>
                <form method="post">
                    {% csrf_token %}
                    {{form.as_table}}
                        <tr>
                            <td>
                                <button type="submit"> Submit </button>
                            </td>
                        </tr>
                </form>
            </table>
    
</body>
</html>
{% endblock %}